### PR TITLE
fix: log cannot be output and log information error

### LINKED ISSUE #100: 插件无法输出日志
之前上传时可以正常输出info级别日志，但是最近发现没日志了
提示
```
SLF4J: A SLF4J service provider failed to instantiate:
org.slf4j.spi.SLF4JServiceProvider: ch.qos.logback.classic.spi.LogbackServiceProvider not a subtype
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
排除s3依赖中的slf4j即可
```
    implementation ('software.amazon.awssdk:s3') {
        exclude group: 'org.slf4j'
    }
```
/assign

### PR DESCRIPTION
**Pull request by longjuan**
```release-note
修复无日志输出的问题
```
fixes #100 
测试上传，关联，删除，解除关联 4种操作的日志
```
---上传---
2023-11-27T22:39:22.139+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=test-1305034426, Key=test/image-pjcl.png, UploadId=17010959629c897f8b8c1a592b0efe300de867a1ea3e891cf04b4f95c6986470a0f30195be)
2023-11-27T22:39:22.391+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="aa84eea735192b49552fa5bf3df317fa")
2023-11-27T22:39:22.547+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://test-1305034426.cos.ap-guangzhou.myqcloud.com/test/image-pjcl.png, Bucket=test-1305034426, Key=test/image-pjcl.png, ETag="afdd5ce39cf49676238fcfc879664b55-1")
2023-11-27T22:39:22.616+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-11-27T14:39:22Z, ContentLength=1420, ETag="afdd5ce39cf49676238fcfc879664b55-1", ContentType=image/png, Metadata={})
2023-11-27T22:39:22.616+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : Upload object test/image-pjcl.png to bucket test-1305034426 successfully
2023-11-27T22:39:22.626+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : Build attachment test/image-pjcl.png successfully
2023-11-27T22:39:29.915+08:00  WARN 7 --- [or-http-epoll-1] ocalVariableTableParameterNameDiscoverer : Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: run.halo.s3os.S3LinkController
---关联---
2023-11-27T22:39:34.657+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : Build attachment test/34.txt successfully
---解除关联---
2023-11-27T22:39:39.937+08:00  INFO 7 --- [tReconciler-t-1] run.halo.s3os.S3OsAttachmentHandler      : Skip deleting object test/34.txt from S3.
---删除---
2023-11-27T22:39:44.290+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: delete object, result: DeleteObjectResponse()
2023-11-27T22:39:44.291+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : Delete object test/image-pjcl.png from bucket test-1305034426 successfully
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

File: src/main/java/run/halo/s3os/S3OsAttachmentHandler.java [hunk 1]
```diff
@@ -216,8 +222,7 @@ Attachment buildAttachment(S3OsProperties properties, ObjectDetail objectDetail)
         var attachment = new Attachment();
         attachment.setMetadata(metadata);
         attachment.setSpec(spec);
-        log.info("Upload object {} to bucket {} successfully", objectDetail.uploadState.objectKey,
-            properties.getBucket());
+        log.info("Build attachment {} successfully", objectDetail.uploadState.objectKey);
```
Comment (JohnNiang) [inline src/main/java/run/halo/s3os/S3OsAttachmentHandler.java:225]:
```suggestion
        log.info("Built attachment {} successfully", objectDetail.uploadState.objectKey);
```

File: src/main/java/run/halo/s3os/S3OsAttachmentHandler.java [hunk 2]
```diff
@@ -368,6 +373,8 @@ Mono<ObjectDetail> upload(UploadContext uploadContext, S3OsProperties properties
                     // build object detail
                     .map((response) -> {
                         checkResult(response, "getMetadata");
+                        log.info("Upload object {} to bucket {} successfully",
```
Comment (JohnNiang) [inline src/main/java/run/halo/s3os/S3OsAttachmentHandler.java:376]:
```suggestion
                        log.info("Uploaded object {} to bucket {} successfully",
```

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Review by ruibaby — APPROVED** [review]
/lgtm
